name: SSH Login

on:
  schedule:
    - cron: '0 0 * * *'  # 每天的北京时间 8 点运行
  workflow_dispatch:

jobs:
  ssh-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install paramiko requests
      
      - name: Download sing.sh
        run: |
          curl -L -o sing.sh https://github.com/feidian8352/serv00-automation/raw/main/sing.sh
          chmod +x sing.sh

      - name: Run Python script
        env:
          SSH_INFO: ${{ secrets.SSH_INFO }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          
        run: python run.py
